import { chromium } from '@playwright/test';
const S = process.env.S;
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--use-gl=swiftshader','--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
const errs = []; page.on('pageerror', (e) => errs.push(String(e)));
await page.goto('http://localhost:4173/?level=7-4&bot=1#play');
await page.waitForFunction(() => window.__syb?.state?.().finished, null, { timeout: 60000 });
await page.waitForTimeout(2500);
await page.screenshot({ path: `${S}/w7-handshake.png` });
await page.waitForSelector('.game-overlay.finale:not([hidden])', { timeout: 15000 });
await page.waitForTimeout(500);
await page.screenshot({ path: `${S}/w7-finale.png` });
console.log('errors', errs);
await browser.close();
